### ISSUE TITLE
Introduce training abstraction

### ISSUE THREAD

**Issue by salwator** [salwator/training_stats#6]
After GPX or any other format is parsed, we should use abstract type for further processing, call it `class Training()`.

## TODO:
- [ ] introduce new type
- [ ] use new type in existing tools
- [ ] encapsulate most used stuff in type
- [ ] implement json dump of gps and hrm data
